export const OTP_LENGTH = 4;

export const FILTERS = ["Distance", "Vehicle", "Amenities", "Time", "Rating"];
export const TEST_EMAILS = ["ssasahil000@gmail.com", "arodos.tech@gmail.com", "sreejindam@gmail.com"];

export const DEFAULT_LAT_LNG = { lat: 26.2006, lng: 92.9376 };
export const STATION_LAT_LNGS = [
	{ id: "1", lat_lng: { lat: 26.2006, lng: 92.9376 }, active: true },
	{ id: "2", lat_lng: { lat: 26.1006, lng: 92.8476 }, active: false },
	{ id: "3", lat_lng: { lat: 26.0592, lng: 92.9876 }, active: false },
];

export const STATIONS: Station[] = [
	{
		id: "1",
		name: "Sangeetha Mobiles Gharepalya EV Charger",
		rating: 4.9,
		distance: 2.5,
		pricePerUnit: 18,
		connectors: ["type1", "type2", "type3"],
		lat_lng: { lat: 26.2006, lng: 92.9376 },
		active: true,
		address: "1st Main road, kudlu Gate, Munireddy Layout, Bandepalya, Garvebhavi Palya, Bengaluru, Karnataka 560068.",
	},
	{
		id: "2",
		name: "Raj Mobiles EV Charger",
		rating: 4.9,
		distance: 2.5,
		pricePerUnit: 18,
		connectors: ["type1", "type2"],
		lat_lng: { lat: 26.1006, lng: 92.8476 },
		active: false,
		address: "12th Street, Kudlu Gate, Munireddy Layout, Bandepalya, Garvebhavi Palya, Bengaluru, Karnataka 560068.",
	},
	{
		id: "3",
		name: "John Gharepalya EV Charger",
		rating: 4.9,
		distance: 2.5,
		pricePerUnit: 18,
		connectors: ["type2", "type3"],
		lat_lng: { lat: 26.1006, lng: 92.9976 },
		active: false,
		address: "12th Street, Kudlu Gate, Munireddy Layout, Bandepalya, Garvebhavi Palya, Bengaluru, Karnataka 560068.",
	},
];

export const TWO_WHEELER_VEHICLES = [
	{
		make: "Ather",
		model: "Ritza",
		battery_capacity: "2.9",
		charging_time_0_100: "8.3hrs",
		charging_time_0_80: "5.45hrs",
		max_power: "4.3kW",
		top_speed: "80kmph",
		image: "arodos/pinev/two-wheelers/ather-ritza.png",
	},
	{
		make: "Ather",
		model: "450X",
		battery_capacity: "2.9",
		charging_time_0_100: "4.3hrs",
		charging_time_0_80: "3.0hrs",
		max_power: "6.4kW",
		top_speed: "90kmph",
		image: "arodos/pinev/two-wheelers/ather-450x.png",
	},
	{
		make: "TVS",
		model: "iCube",
		battery_capacity: "2.2",
		charging_time_0_100: "5hrs",
		charging_time_0_80: "2.45hrs",
		max_power: "4.4kW",
		top_speed: "75kmph",
		image: "arodos/pinev/two-wheelers/tvs-icube.png",
	},
	{
		make: "OLA",
		model: "S1",
		battery_capacity: "3",
		charging_time_0_100: "6.5hrs",
		charging_time_0_80: "7.15hrs",
		max_power: "11kW",
		top_speed: "117kmph",
		image: "arodos/pinev/two-wheelers/ola-s1.png",
	},
	{
		make: "VIDA",
		model: "V2",
		battery_capacity: "2.2",
		charging_time_0_100: null,
		charging_time_0_80: "3.3hrs",
		max_power: "6kW",
		top_speed: "69kmph",
		image: "arodos/pinev/two-wheelers/vida-v2.png",
	},
	{
		make: "VIDA",
		model: "VX2+",
		battery_capacity: "3.4",
		charging_time_0_100: "5.39hrs",
		charging_time_0_80: "4.13hrs",
		max_power: "6kW",
		top_speed: "80kmph",
		image: "arodos/pinev/two-wheelers/vida-vx2_plus.png",
	},
	{
		make: "RIVER",
		model: "Indie",
		battery_capacity: "4",
		charging_time_0_100: "6hrs",
		charging_time_0_80: "5hrs",
		max_power: "6.7kW",
		top_speed: "90kmph",
		image: "arodos/pinev/two-wheelers/river-indie.png",
	},
	{
		make: "BGauss",
		model: "C12",
		battery_capacity: "2",
		charging_time_0_100: "4.5hrs",
		charging_time_0_80: "3.15hrs",
		max_power: "2.5kW",
		top_speed: "60kmph",
		image: "arodos/pinev/two-wheelers/bgauss-c12.png",
	},
	{
		make: "Okinawa",
		model: "Praise",
		battery_capacity: "3.3",
		charging_time_0_100: "3hrs",
		charging_time_0_80: "2hrs",
		max_power: "2.5kW",
		top_speed: "58kmph",
		image: "arodos/pinev/two-wheelers/okinawa-praise.png",
	},
	{
		make: "Ampere",
		model: "Nexus",
		battery_capacity: "3.3",
		charging_time_0_100: "3.3hrs",
		charging_time_0_80: "2hrs",
		max_power: "3.3kW",
		top_speed: "93kmph",
		image: "arodos/pinev/two-wheelers/ampere-nexus.png",
	},
];
