import {
	ArrowLeft,
	Bell,
	BookmarkIcon,
	CalendarIcon,
	CheckIcon,
	ChevronRightIcon,
	CircleDotIcon,
	EllipsisVertical,
	IndianRupeeIcon,
	Loader2,
	MapPinIcon,
	NavigationIcon,
	PhoneIcon,
	SearchIcon,
	StarIcon,
	UserIcon,
	EyeIcon,
	Plus,
	MailIcon,
	MessageCircle,
	StoreIcon,
	XIcon,
	BanIcon,
	SearchXIcon,
	EditIcon,
	BoltIcon,
	RefreshCcwIcon,
	BatteryChargingIcon,
	ClockIcon,
	QrCodeIcon,
	RouteIcon,
	HistoryIcon,
	CopyIcon,
	DownloadIcon,
	FileTextIcon,
	StopCircleIcon,
	AlertTriangleIcon,
	SettingsIcon,
	ThermometerIcon,
	ActivityIcon,
	WalletIcon,
	ShieldIcon,
	HelpCircleIcon,
	LogOutIcon,
	CarIcon,
	BadgeCheckIcon,
	TagIcon,
	PaletteIcon,
	BatteryIcon,
	TrashIcon,
	PauseIcon,
	UploadIcon,
	CopyCheckIcon,
	CopyXIcon,
	PowerIcon,
} from "lucide-react";
import { SVGIcons } from "./SVGIcons";

export const Icons = {
	...SVGIcons,

	//* LUCIDE ICONS *//
	AlertTriangleIcon,
	LoadingIcon: Loader2,
	ArrowLeftIcon: ArrowLeft,
	BellIcon: Bell,
	ThreeDotIcon: EllipsisVertical,
	CalendarIcon,
	PhoneIcon,
	ChevronRightIcon,
	SearchIcon,
	BookmarkIcon,
	StarIcon,
	NavigationIcon,
	IndianRupeeIcon,
	MapPinIcon,
	CircleDotIcon,
	UserIcon,
	CheckIcon,
	EyeIcon,
	AddIcon: Plus,
	MailIcon,
	MessageCircleIcon: MessageCircle,
	StoreIcon,
	CloseIcon: XIcon,
	BanIcon,
	SearchXIcon,
	EditIcon,
	BoltIcon,
	RefreshCcwIcon,
	BatteryChargingIcon,
	ClockIcon,
	QrCodeIcon,
	RoadIcon: RouteIcon,
	HistoryIcon,
	CopyIcon,
	DownloadIcon,
	FileTextIcon,
	StopIcon: StopCircleIcon,
	SettingsIcon,
	ThermometerIcon,
	ActivityIcon,
	WalletIcon,
	ShieldIcon,
	HelpCircleIcon: HelpCircleIcon,
	LogOutIcon,
	CarIcon,
	BadgeCheckIcon,
	TagIcon,
	PaletteIcon,
	BatteryIcon,
	TrashIcon,
	PauseIcon,
	UploadIcon,
	CopyCheckIcon,
	CopyXIcon,
	PowerIcon,
};

export type Icon = keyof typeof Icons;
